### ISSUE TITLE
Accounting for Area of Land vs. Water

### ISSUE THREAD

**Issue by kmcinerny** [Carceral-Ecologies/LA_Law_Enforcement_Heli#104]
When taking census tract area into consideration for the inferential statistics about demographics/ flight time, does it matter to distinguish between land vs water? I don't think so but am open to suggestions, and census area square meters includes both.

**Comment by shapironick** [comment]
this is a great question! I assume primarily of impact on the coast and
maybe silverlake/echo park lake. I agree with no, but maybe we could just
table this for now (leaving the issue open) as we might want to consider
this further down the line as we are really crossing our t's and dotting
our i's

**Comment by kmcinerny** [comment]
Sounds good
