### ISSUE TITLE
controlling for LAPD's effect on neighborhood flight hours

### ISSUE THREAD

**Issue by kmcinerny** [Carceral-Ecologies/LA_Law_Enforcement_Heli#107]
I'm wondering if I should create a dummy variable of whether a census tract falls within the City of LA- and how that might affect the racial demographic marginal effects (since LAPD has flight times way higher than any other police department). For example, the marginal effect of the Latinx population size on flight hours is currently inverse: i.e. higher Latinx populations see exponentially fewer flight hours. I wonder if this could be because many neighborhoods/tracts that with high Latinx populations fall outside the City (though many fall within it too so this could be wrong). At the same time, though, this is people's lived experiences, so if LAPD is deployed more than the sheriffs or other municipalities that says something too about how people within LA city are being surveilled more than those in other areas of the County.

**Comment by shapironick** [comment]
Sounds very smart! It would also be interesting to see when LAPD is
surveilling people outside of their jurisdiction. We'll certainly be
sensitive in how we frame this so as not to discount the impacts of lesser
surveilled communities. I also wonder if there are hight differences
between LAPD and LASD flights.

**Comment by shapironick** [comment]
in terms of altitude (sorry!)
