### ISSUE TITLE
Assigning Census Tracts to Neighborhoods

### ISSUE THREAD

**Issue by kmcinerny** [Carceral-Ecologies/LA_Law_Enforcement_Heli#109]
Make note of [this resource](https://usc.data.socrata.com/Los-Angeles/Census-Tract-Locations-LA-/atat-mmad) for finding the neighborhoods in which each census tract belongs. (Though need to look more closely at how they deal with tracts that overlap between multiple neighborhoods).

I used this to add neighborhoods within LA City as a variable in the generalized linear model. Adding all the neighborhoods allows me (hopefully) to condense datasets - as I currently have two separate datasets for flight times by neighborhood and flight times by tract. With this set I can just add up the flight times of the tracts in each respective neighborhood.

**Comment by kmcinerny** [comment]
This may be an issue, though, because some tracts don't have assigned neighborhoods. Also, at least one neighborhood within the city of LA is labeled as part of "Long Beach" with this data....

**Comment by kmcinerny** [comment]
Actually that ^ might not be the case... rather the issue is that some census tracts overlap with LA city but do not fit neatly within it (see map below- the purple is when I clip the tracts to the City of LA Boundary, but the gray shows the additional area of tracts on the border between city of LA and neighboring cities/areas). So should I include or exclude those areas (and instead only include the tracts that fall completely within LA city)? Or should I define LAPD jurisdiction differently?

**Comment by kmcinerny** [comment]
*for now* I'm going to keep it as all those tracts that overlap with the City of LA, whether they're squarely within it or split between it and bordering cities/ areas. This is because LAPD helicopters don't likely fly perfectly within city limits, and their noise/other effects likely also affects surrounding areas (like border areas on either side of South Central Ave near Watts).

**Comment by shapironick** [comment]
I agree! you could make a map later of all of the census tracts that fit
fully w/in LA city in one color and all of the included tracts that are
partially in LA city in another color.

**Comment by kmcinerny** [comment]
Note that I will Redo the spatial clip so that the “CityofLA” variable only includes tracts that fall within it, not those that are surrounding
