### ISSUE TITLE
Review method of excluding altitude outliers

### ISSUE THREAD

**Issue by kmcinerny** [Carceral-Ecologies/LA_Law_Enforcement_Heli#11]
It would be helpful to have a third party review our method of [finding-outlier-altitudes](https://github.com/kmcinerny/LA_Law_Enforcement_Heli/blob/main/data-cleaning/R-data-cleaning/find-outlier-altitudes.R) based on ascension/descension rates of 1600 ft/min (plus a little wiggle room- so up to 2000 ft/min). I noticed how some of the graphs of altitude over time still seem to have some issues (steep drops, gaps, slopes) even after we exclude outliers with this method. What to do with those?

**Comment by shapironick** [comment]
absolutely! i think this is something to ask John Wiseman when we have a bunch of itemized questions to ask him

**Comment by kmcinerny** [comment]
Also maybe this is a code issue, because it excludes altitude outliers based on the difference from last valid point (not from points that would have been excluded).

**Comment by kmcinerny** [comment]
Kristian thoughts: bundle this with one of my research questions (i.e. on altitude ranges)
