### ISSUE TITLE
hours by tail number discrepancies/ NA values

### ISSUE THREAD

**Issue by kmcinerny** [Carceral-Ecologies/LA_Law_Enforcement_Heli#118]
I have two versions of hrs_per_aircraft(_2), with slightly different results (different tot_time by minutes/hrs, but very similar). 

I don't know why these are different. I thought it was because in the older one (from Nov 16) I didn't have arrange(flight_id, timestamp), but in my current code I do, and I'm actually getting results that are the same as the Nov 16 code. I didn't push to Git on Jan 27, when I got different output results. But I just realized I had staged a commit (not sure when) that I never pushed to Git.

Maybe when I rewrote/ran the script on November 16, the data had already been arranged by flight id and timestamp as part of a different function, so I didn't need to run it again in this script and the output was right. Then maybe on Jan 27 I ran it again, saw that the results were different, and realized I needed to add the arrange(flight_id, timestamp) in the code.

Because I didn't properly document, I'm still pretty stuck on what the difference is.

The Nov16/current results I'm getting have NA values, and I'm not exactly sure where they come from. It could be that some of the flights are missing values in the year-month column. If that is the case, should I exclude those points from the analysis? I don't even see why that would make a difference though, since those points are either excluded altogether or they are marked as NA-- pretty sure they wouldn't be included in a different month.

Should I just keep the newest version since the script seems right?

**Comment by shapironick** [comment]
is it possible to run the nov16 script and exclude those with NA in the
year-month column and see if it matches jan 27?

If you don't see a problem w/ the newest script and jacobo reviews it, than
its ok to keep that one and just improve documentation going forward.
