### ISSUE TITLE
Questions for data analysis

### ISSUE THREAD

**Issue by kmcinerny** [Carceral-Ecologies/LA_Law_Enforcement_Heli#13]
- Number of flights in each hour of the day (across the year) per neighborhood?
- How frequently and where do they orbit during sleeping hours?
- Where are low-flying areas and how long do they fly within a particular (low) altitude range?  
- Flights per department?
- Flights per neighborhood separated by department?
- Some way of accounting for neighborhood area when calculating flight times?
- Average flight times (landing-takeoff or last position-first?)
- Case studies of specific neighborhoods (esp. CSP areas) at certain times of day
- Total flight hours (so we can calculate cost)
- What percent of positions were in each neighborhood?
- Time spent in transit vs. in orbit?
- Total flights for each aircraft (so we can calculate emissions)- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by shapironick** [comment]
By flights per hour do you mean flights for the full year for each of the 24 hours in the day? 

or do you mean flight time per x? 

Orbits in neighborhoods at sleeping hours seems important. 

lower altitude (we would need to establish a threshold) also seems to be an important variable for the sleeping hours and the circling as John was raising the point that sometimes the circles are high (but i have never seen that personally)

**Comment by kmcinerny** [comment]
Could turn this into a milestone and separate issues for each research question
