### ISSUE TITLE
Flight Emissions Calculation

### ISSUE THREAD

**Issue by kmcinerny** [Carceral-Ecologies/LA_Law_Enforcement_Heli#34]
In calculating emissions, will I have to distinguish between whether a flight is at fast cruise speed or recommended cruise speed? See [this report p. 51-52](https://global-helicopter-service.com/wp-content/uploads/2018/04/AS350B3-tech_data_2009-1.pdf)

**Comment by shapironick** [comment]
I think for now to make this first pass more straight forward for you I think you can assume recommended and then when/if we get more funding you can spend the time to change between the two. 

Are you going to be using altitude to calc this? 

Also for later, this chart assumes a new engine so we could later add a correction factor later for reduced efficiency over time.  

Sent on the move
