### ISSUE TITLE
Orbit altitudes

### ISSUE THREAD

**Issue by kmcinerny** [Carceral-Ecologies/LA_Law_Enforcement_Heli#45]
How to visualize the range of altitudes when flights are in orbit? Do I take every data point into account? Do I take averages?

**Comment by shapironick** [comment]
Calculating the altitude range in a single orbit could be a helpful place
to start! then you could do a hist of the ranges to get a feel of how much
variation in altitude in an orbit is common.

I think finding a long duration orbit above oen of the CBP cites and simply
plotting that in space would be affectively interesting and helpful for
storytelling.
