### ISSUE TITLE
Flight hours for smaller neighborhoods and census tracts

### ISSUE THREAD

**Issue by kmcinerny** [Carceral-Ecologies/LA_Law_Enforcement_Heli#51]
Instead of combining west and eastside south central, keep individual neighborhoods and run demographic analysis, and/or use census tracts

**Comment by shapironick** [comment]
how does assigning demographics work to the n'hood map? are we making some
approximations when an n'hood line bisects the data units of the
demographics?

**Comment by kmcinerny** [comment]
I'm using USC [Neighborhood Data for Social Change](https://map.myneighborhooddata.org/), which I believe combined demographics from census blocks that fit within respective LA Times Neighborhoods. They provide percentages of each demographic along with a total population figure for each neighborhood (for 2019). I multiplied those to get populations of each demographic group, then summed the populations in the neighborhoods that made up west- and eastside south central.
Does that answer your question?

**Comment by shapironick** [comment]
yes thank you! its so strange that their website doesn't have more detail
on their methods. no need to dig further! thank you!
