### ISSUE TITLE
How often should I pull request?

### ISSUE THREAD

**Issue by kmcinerny** [Carceral-Ecologies/LA_Law_Enforcement_Heli#8]
Should I create a pull request to Carceral-ecologies-main after committing and pushing each new big change? Or after a group of changes?

**Comment by shapironick** [comment]
Don't worry about pull requests! a pull request is used most often in situations where you want your code reviewed before it gets merged but on projects that are a single person you can just go ahead and merge. often people writing code don't have permission to merge so they have to submit a request. Like any random person on the internet can see your code and submit a pull request. tl;dr you don't need to do pull requests on this project at this phase.
