### ISSUE TITLE
Loop

### ISSUE THREAD

**Issue by kmcinerny** [Carceral-Ecologies/LA_Law_Enforcement_Heli#86]
If I run the loop through each function, the way it's currently structured will create one large dataset of all the months at the end of the function. 

If I did this once at the beginning (add-flight-id-nullpos) function, that could work. But that creates a dataset with 11 million rows, which I would likely need to run through the deep learning machine if I want to run the functions on it.

I could individually run each position through the function, but loops in subsequent functions (convert-time, exclude outliers) would also combine them when they would need to be kept separate.

So I either need to write the loop differently or use the deep learning machine.

**Comment by shapironick** [comment]
you're doing great, kate! maybe you can bring this code back to the data
science people to ask for them to help with the loop or give us access to
the deep learning machine.

if they don't help w/ either is it possible that I can just rent space on
such a machine? I also have a virtual machine in Life Sciences but I have
no idea about how to use it...

**Comment by kmcinerny** [comment]
Thank you for the feedback. I sent an email to them with that exact request so i’ll see what they say. 

If it’s not possible to use their machine, maybe I can ask if they have resources for how we might be able to use our own.

**Comment by shapironick** [comment]
perfect, thank you!
