### ISSUE TITLE
Error in year-long neighborhood flight analysis

### ISSUE THREAD

**Issue by kmcinerny** [Carceral-Ecologies/LA_Law_Enforcement_Heli#96]
https://github.com/Carceral-Ecologies/LA_Law_Enforcement_Heli/blob/6e68962ccb6d0a173e4c2d17bce25416a92be37e/src/summary-stats/neighborhood-flight-times.R#L31

The error when I run this whole code says 
```
Error in UseMethod("group_by") :
no applicable method for 'group_by' applied to an object of class "c('double', 'numeric')"
```
I thought maybe this was an issue with the flight_id, which had slightly changed since I combined all the months. So in line 26 I converted flight_id to a string (though it might have already been one). However, I ran into the same error

**Comment by shapironick** [comment]
Is this first answer possibly helpful? might be a syntax error between plyr
+ dplyr?

https://stackoverflow.com/questions/45986155/r-error-in-usemethodgroups-no-applicable-method-for-groups-applied-to

**Comment by kmcinerny** [comment]
Thanks for sending. There might be a little overlap, though the forum is mostly discussing the "count" function, where I am using "group_by." I will keep looking, because this might be a similar kind of issue.

**Comment by kmcinerny** [comment]
I think I fixed it here https://github.com/Carceral-Ecologies/LA_Law_Enforcement_Heli/commit/e86f476375a01a9b48f207a565c5bdf0eb51c6f2 by taking it out of the function. Now I just have to double check the numbers I got, but they seem pretty right.
